#!/bin/bash

# Environment setup:
{
module -force purge
module load Stages/2022 GCC/11.2.0 OpenMPI/4.1.1
module load CDO/2.0.2
module load NCO
module load xarray Python matplotlib
} &> /dev/null


source directories.sh